# Generated by Django 4.2.3 on 2023-07-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_school_class_strength_school_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='School_name1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='app1.school'),
        ),
    ]
