# Generated by Django 4.2.3 on 2023-07-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_student_school_name1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='School_name1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_rel', to='app1.school'),
        ),
    ]
